import type { Metadata } from "next";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "./(routes)/(root)/Components/AppSidebar/AppSidebar";
import { Footer, Navbar } from "@/components/Shared";




const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${spaceGrotesk.variable} antialiased`}>
          <SidebarProvider>
            <AppSidebar/>
            <div className="w-full bg-stone-100 flex flex-col min-h-screen">
                <Navbar/>
          
                <main className="flex-1">{children}</main>
                <Footer/>
             </div>
          </SidebarProvider>
         
        </body>
      </html>
    </ClerkProvider>
  );
}
